const lebowbpWerkzaamhedenTonen = () => {
    const x = document.getElementById("lebowbpwerkzaamheden");
    if (x.style.display === "none") {
        x.style.display = "block";
        document.getElementById("lebowbpbutton").innerHTML = "Werkzaamheden verbergen";
    } else {
        x.style.display = "none";
        document.getElementById("lebowbpbutton").innerHTML = "Werkzaamheden tonen";
    }
};

const asteriaManagerWerkzaamhedenTonen = () => {
    const x = document.getElementById("asteriamanagerwerkzaamheden");
    if (x.style.display === "none") {
        x.style.display = "block";
        document.getElementById("asteriamanagerbutton").innerHTML = "Werkzaamheden verbergen";
    } else {
        x.style.display = "none";
        document.getElementById("asteriamanagerbutton").innerHTML = "Werkzaamheden tonen";
    }
};

const dfdsWerkzaamhedenTonen = () => {
    const x = document.getElementById("dfdswerkzaamheden");
    if (x.style.display === "none") {
        x.style.display = "block";
        document.getElementById("dfdsbutton").innerHTML = "Werkzaamheden verbergen";
    } else {
        x.style.display = "none";
        document.getElementById("dfdsbutton").innerHTML = "Werkzaamheden tonen";
    }
};

const pachoWerkzaamhedenTonen = () => {
    const x = document.getElementById("pachowerkzaamheden");
    if (x.style.display === "none") {
        x.style.display = "block";
        document.getElementById("pachobutton").innerHTML = "Werkzaamheden verbergen";
    } else {
        x.style.display = "none";
        document.getElementById("pachobutton").innerHTML = "Werkzaamheden tonen";
    }
};

const asteriaMedewerkerWerkzaamhedenTonen = () => {
    const x = document.getElementById("asteriamedewerkerwerkzaamheden");
    if (x.style.display === "none") {
        x.style.display = "block";
        document.getElementById("asteriamedewerkerbutton").innerHTML = "Werkzaamheden verbergen";
    } else {
        x.style.display = "none";
        document.getElementById("asteriamedewerkerbutton").innerHTML = "Werkzaamheden tonen";
    }
};

const sjalotWerkzaamhedenTonen = () => {
    const x = document.getElementById("sjalotwerkzaamheden");
    if (x.style.display === "none") {
        x.style.display = "block";
        document.getElementById("sjalotbutton").innerHTML = "Werkzaamheden verbergen";
    } else {
        x.style.display = "none";
        document.getElementById("sjalotbutton").innerHTML = "Werkzaamheden tonen";
    }
};

const festivalWerkzaamhedenTonen = () => {
    const x = document.getElementById("festivalwerkzaamheden");
    if (x.style.display === "none") {
        x.style.display = "block";
        document.getElementById("festivalbutton").innerHTML = "Werkzaamheden verbergen";
    } else {
        x.style.display = "none";
        document.getElementById("festivalbutton").innerHTML = "Werkzaamheden tonen";
    }
};

const tasteWerkzaamhedenTonen = () => {
    const x = document.getElementById("tastewerkzaamheden");
    if (x.style.display === "none") {
        x.style.display = "block";
        document.getElementById("tastebutton").innerHTML = "Werkzaamheden verbergen";
    } else {
        x.style.display = "none";
        document.getElementById("tastebutton").innerHTML = "Werkzaamheden tonen";
    }
};

const clausWerkzaamhedenTonen = () => {
    const x = document.getElementById("clauswerkzaamheden");
    if (x.style.display === "none") {
        x.style.display = "block";
        document.getElementById("clausbutton").innerHTML = "Werkzaamheden verbergen";
    } else {
        x.style.display = "none";
        document.getElementById("clausbutton").innerHTML = "Werkzaamheden tonen";
    }
};

const rivaWerkzaamhedenTonen = () => {
    const x = document.getElementById("rivawerkzaamheden");
    if (x.style.display === "none") {
        x.style.display = "block";
        document.getElementById("rivabutton").innerHTML = "Werkzaamheden verbergen";
    } else {
        x.style.display = "none";
        document.getElementById("rivabutton").innerHTML = "Werkzaamheden tonen";
    }
};

const jachtslotWerkzaamhedenTonen = () => {
    const x = document.getElementById("jachtslotwerkzaamheden");
    if (x.style.display === "none") {
        x.style.display = "block";
        document.getElementById("jachtslotbutton").innerHTML = "Werkzaamheden verbergen";
    } else {
        x.style.display = "none";
        document.getElementById("jachtslotbutton").innerHTML = "Werkzaamheden tonen";
    }
};

const parcsWerkzaamhedenTonen = () => {
    const x = document.getElementById("parcswerkzaamheden");
    if (x.style.display === "none") {
        x.style.display = "block";
        document.getElementById("parcsbutton").innerHTML = "Werkzaamheden verbergen";
    } else {
        x.style.display = "none";
        document.getElementById("parcsbutton").innerHTML = "Werkzaamheden tonen";
    }
};

const kisteWerkzaamhedenTonen = () => {
    const x = document.getElementById("kistewerzaamheden");
    if (x.style.display === "none") {
        x.style.display = "block";
        document.getElementById("kistebutton").innerHTML = "Werkzaamheden verbergen";
    } else {
        x.style.display = "none";
        document.getElementById("kistebutton").innerHTML = "Werkzaamheden tonen";
    }
};



/*
const werkzaamhedenButtonArray = document.getElementsByClassName("werkzaamhedenbutton");
const werkzaamhedenArray = document.getElementsByClassName("werkzaamheden");

const werkzaamhedentonen = (event) => {
    switch (event.target) {
        case werkzaamhedenButtonArray[0]:
            x = werkzaamhedenArray[0];
            if (x.style.display === "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            };
            break;
    }
};
WERKT NIET
*/
