/* const lebowbpWerkzaamhedenTonen = () => {
    const x = document.getElementById("lebowbpwerkzaamheden");
    if (x.style.display === "none") {
        x.style.display = "block";
        document.getElementById("lebowbpbutton").innerHTML = "Werkzaamheden verbergen";
    } else {
        x.style.display = "none";
        document.getElementById("lebowbpbutton").innerHTML = "Werkzaamheden tonen";
    }
}; */



/*
const werkzaamhedenButtonArray = document.getElementsByClassName("werkzaamhedenbutton");
const werkzaamhedenArray = document.getElementsByClassName("werkzaamheden");

const werkzaamhedentonen = (event) => {
    switch (event.target) {
        case werkzaamhedenButtonArray[0]:
            x = werkzaamhedenArray[0];
            if (x.style.display === "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            };
            break;
    }
};
WERKT NIET
*/
